### ISSUE TITLE
Game crashes and gives me an error

### ISSUE THREAD

**Issue by DatGuyDebeloper** [EfeDursun125/CS-EBOT#1]
game crashes and just says this "MSG_ONE or MSG_ONE_UNRELIABLE with no target entity" I was 7 seconds into the game when this happens everytime.

**Comment by EfeDursun125** [comment]
try this: https://github.com/EfeDursun125/CS-EBOT/releases/tag/1.02b

if game crashes again send your latest dump file to me.
dump files can be found at here: "Program Files (x86)\Steam\dumps"

**Comment by EfeDursun125** [comment]
also maybe old waypoint files can cause the crash for some reason, save your old waypoints and try recreate waypoints for the map

**Comment by DatGuyDebeloper** [comment]
I'll try that some other time because I'm still testing my waypoints for ze maps. Thanks for the fix.

**Comment by EfeDursun125** [comment]
it worked?
