### ISSUE TITLE
where is linux version?

### ISSUE THREAD

**Issue by TheArtemMaps** [EfeDursun125/CS-EBOT#12]
you are saying that there is linux unofficial version, but i can't find it anywhere. where is it?

**Comment by EfeDursun125** [comment]
download release 1.01

**Comment by Nord1cWarr1or** [comment]
@EfeDursun125 `[META] ERROR: dll: Failed query plugin '<ebot.so>'; Couldn't open file '/home/maks/LGSM/serverfiles/cstrike/addons/ebot/dlls/ebot.so': /home/maks/LGSM/serverfiles/cstrike/addons/ebot/dlls/ebot.so: undefined symbol: ebot_knifemode`

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or can you try this? [ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11054137/ebot.zip)

Yep, just tested it, and it says the same, `undefined symbol: ebot_knifemode`

**Comment by EfeDursun125** [comment]
@Nord1cWarr1or sorry for taking your time but i think this will work, i tried to link required libs to ebot, as you see size is increased can you try this?
[ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11056790/ebot.zip)

**Comment by Nord1cWarr1or** [comment]
@EfeDursun125 sure, I want to help with this so that we have a Linux version of your project.

I tested it, and now it shows another "undefined symbol": `ebot_gamemod`

**Comment by EfeDursun125** [comment]
does "ebot addbot" command works? and what exactly it says?

**Comment by EfeDursun125** [comment]
@Nord1cWarr1or by the way commands are changed in newer versions thats why it says unknown command it chaned to ebot_gamemode it seems ebot.cfg is called when you open a map because it loads old commands which is changed in newer versions, can you try the .so file with ebot 1.06 files?

**Comment by Nord1cWarr1or** [comment]
> does "ebot addbot" command works? and what exactly it says?

No, it just not started. 
`[ 5] <ebot.so>        badf load  ebot.so                     v -              ini   -     -`

```
L 03/24/2023 - 01:27:52: [META] ERROR: dll: Failed query plugin '<ebot.so>'; Couldn't open file '/home/maks/LGSM/serverfiles/cstrike/addons/ebot/dlls/ebot.so': /home/maks/LGSM/serverfiles/cstrike/addons/ebot/dlls/ebot.so: undefined symbol: ebot_gamemod
L 03/24/2023 - 01:27:52: [META] ERROR: dll: Skipping plugin '<ebot.so>'; couldn't query
L 03/24/2023 - 01:27:52: [META] ERROR: dll: Couldn't close plugin file 'ebot.so': invalid handle
L 03/24/2023 - 01:27:52: [META] ERROR: dll: Failed to load plugin 'ebot.so'
```

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or by the way commands are changed in newer versions thats why it says unknown command it chaned to ebot_gamemode it seems ebot.cfg is called when you open a map because it loads old commands which is changed in newer versions, can you try the .so file with ebot 1.06 files?

I assumed that, so I already used the configs from the last "release"

**Comment by EfeDursun125** [comment]
@Nord1cWarr1or i'm asking last time, can you try this?
[ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11069816/ebot.zip)

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or i'm asking last time, can you try this? [ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11069816/ebot.zip)

Sure, I can test it. 
Now the error is as follows:
```
L 03/26/2023 - 06:27:12: [META] ERROR: dll: Failed query plugin '<ebot.so>'; Couldn't find Meta_Query(): function not found
L 03/26/2023 - 06:27:12: [META] ERROR: dll: Skipping plugin '<ebot.so>'; couldn't query
L 03/26/2023 - 06:27:12: [META] ERROR: dll: Couldn't close plugin file 'ebot.so': invalid handle
```

**Comment by EfeDursun125** [comment]
@Nord1cWarr1or sorry for taking your time
[ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11072166/ebot.zip)

**Comment by Nord1cWarr1or** [comment]
@EfeDursun125 don't worry about it. :)

Now it says:
`[META] ERROR: dll: Failed query plugin '<ebot.so>'; Couldn't find GiveFnptrsToDll(): function not found`

**Comment by EfeDursun125** [comment]
@Nord1cWarr1or this is working, tested on a linux pc
[ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11073068/ebot.zip)

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or this is working, tested on a linux pc [ebot.zip](https://github.com/EfeDursun125/CS-EBOT/files/11073068/ebot.zip)

Yes! This version is work for me. But not properly. I will create another issue. Thanks anyway.
