### ISSUE TITLE
[QUESTION] About bots.

### ISSUE THREAD

**Issue by HellMan2023** [EfeDursun125/CS-EBOT#14]
@EfeDursun125,
Hello, dear developer, I wanted to ask you about the **ebotasync.dll** file. Can you tell me what it is for please? It's just that information about this is not indicated anywhere (or I did not find it), so I decided to ask.

**Comment by EfeDursun125** [comment]
async version of ebot, does not work on xash and it removes lagspikes like pathfinding on a map with 2000-4000 waypoints (normally around 200-800, less waypoints = better performance)

**Comment by HellMan2023** [comment]
Understood. Thanks for the quick response )
