### ISSUE TITLE
Add files via upload

### ISSUE THREAD

**Issue by prsyahmi** [EfeDursun125/CS-EBOT#20]
Hi, sorry for opening this issue but I'm actually curious as why you use file upload instead of with git.

**Comment by EfeDursun125** [comment]
Hi, there's no reason.

**Comment by prsyahmi** [comment]
Hi @EfeDursun125
It seems you know things around github and have plenty of experience, that makes me curious :)

However if you are looking for recommendations, on windows, there is Git interfaces such as: TortoiseGit (simple and is ok), and modern equivalent: Sublime Merge, Github Desktop, GitKraken (free for public repo, nice ui but has most issues) - sorted by my preferences.

On linux there is Sublime Merge, Github Desktop, GitKraken, GitCola, etc - not sorted by my preference, I rarely coding on linux.

With git, you can avoid maintaining two copies, on your local computer and github especially when deleting files. "Linking" local git with github is simply by using public-private key pair.

I will close this issue, thanks for replying.
