### ISSUE TITLE
Linux deps

### ISSUE THREAD

**Issue by l00k** [EfeDursun125/CS-EBOT#22]
What do you use to build on Linux?
I tried various GCC versions, various CXX versions.
But keep failing.
Any list of deps?
I also see errors in code. What is last buildable revision?

I will definitively prepare docker for that.

EDIT: I was able to build few releases (based on tags). In all are some Cpp issues which I had to fix before building.
But sadly all have issue with waypoint paths.

Best if you could share what revision was used to build 1.07 LEGACy

I wanted to join discord - but all invite links which I've found already expired.

**Comment by EfeDursun125** [comment]
Hi, install clang and try again with updated source. Currently it crashes on linux and i have no idea how to debug on linux.

There is updated.source.code.zip
https://github.com/EfeDursun125/CS-EBOT-LEGACY/releases/tag/R12

Link is working btw.
https://discord.com/invite/v7PesBamXt

**Comment by l00k** [comment]
Thx
