### ISSUE TITLE
Linux version where?

### ISSUE THREAD

**Issue by Skumek** [EfeDursun125/CS-EBOT#7]
Not many people uses windows except for testing things. Can you get linux version of this so we can use for public servers?

Very intrested in this for my mods+experiments and i would credit you.

Thanks :)

**Comment by EfeDursun125** [comment]
I can't compile it for linux, older versions aren't compiled by me. About testing; just play with them and if it crashes send me dump file or debug it yourself with WinDBG which is shows what function is causing the crash and shows the line of function where is used.

Compile it for linux by yourself if you can.

**Comment by EfeDursun125** [comment]
now linux version is in beta, go to releases select 1.07b Linux
